// Generated by gencpp from file perception/Objects.msg
// DO NOT EDIT!


#ifndef PERCEPTION_MESSAGE_OBJECTS_H
#define PERCEPTION_MESSAGE_OBJECTS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <perception/Object.h>
#include <sensor_msgs/Image.h>

namespace perception
{
template <class ContainerAllocator>
struct Objects_
{
  typedef Objects_<ContainerAllocator> Type;

  Objects_()
    : header()
    , objects()
    , frame()  {
    }
  Objects_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , objects(_alloc)
    , frame(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::perception::Object_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::perception::Object_<ContainerAllocator> >::other >  _objects_type;
  _objects_type objects;

   typedef  ::sensor_msgs::Image_<ContainerAllocator>  _frame_type;
  _frame_type frame;





  typedef boost::shared_ptr< ::perception::Objects_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::perception::Objects_<ContainerAllocator> const> ConstPtr;

}; // struct Objects_

typedef ::perception::Objects_<std::allocator<void> > Objects;

typedef boost::shared_ptr< ::perception::Objects > ObjectsPtr;
typedef boost::shared_ptr< ::perception::Objects const> ObjectsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::perception::Objects_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::perception::Objects_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::perception::Objects_<ContainerAllocator1> & lhs, const ::perception::Objects_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.objects == rhs.objects &&
    lhs.frame == rhs.frame;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::perception::Objects_<ContainerAllocator1> & lhs, const ::perception::Objects_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace perception

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::perception::Objects_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::perception::Objects_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::perception::Objects_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::perception::Objects_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::perception::Objects_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::perception::Objects_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::perception::Objects_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f6393f2ba536fb9c0b95348c35d4a1c9";
  }

  static const char* value(const ::perception::Objects_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf6393f2ba536fb9cULL;
  static const uint64_t static_value2 = 0x0b95348c35d4a1c9ULL;
};

template<class ContainerAllocator>
struct DataType< ::perception::Objects_<ContainerAllocator> >
{
  static const char* value()
  {
    return "perception/Objects";
  }

  static const char* value(const ::perception::Objects_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::perception::Objects_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"Object[] objects\n"
"\n"
"sensor_msgs/Image frame\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: perception/Object\n"
"std_msgs/Header                 header\n"
"uint32                          id\n"
"string                          label\n"
"int32                           class_num\n"
"float32                         score   #Score as defined by the detection, Optional\n"
"############### 2D Rect\n"
"int32                           xmin           # X coord in image space(pixel) of the initial point of the Rect\n"
"int32                           ymin           # Y coord in image space(pixel) of the initial point of the Rect\n"
"int32                           xmax       # Width of the Rect in pixels\n"
"int32                           ymax      # Height of the Rect in pixels\n"
"\n"
"\n"
"================================================================================\n"
"MSG: sensor_msgs/Image\n"
"# This message contains an uncompressed image\n"
"# (0, 0) is at top-left corner of image\n"
"#\n"
"\n"
"Header header        # Header timestamp should be acquisition time of image\n"
"                     # Header frame_id should be optical frame of camera\n"
"                     # origin of frame should be optical center of camera\n"
"                     # +x should point to the right in the image\n"
"                     # +y should point down in the image\n"
"                     # +z should point into to plane of the image\n"
"                     # If the frame_id here and the frame_id of the CameraInfo\n"
"                     # message associated with the image conflict\n"
"                     # the behavior is undefined\n"
"\n"
"uint32 height         # image height, that is, number of rows\n"
"uint32 width          # image width, that is, number of columns\n"
"\n"
"# The legal values for encoding are in file src/image_encodings.cpp\n"
"# If you want to standardize a new string format, join\n"
"# ros-users@lists.sourceforge.net and send an email proposing a new encoding.\n"
"\n"
"string encoding       # Encoding of pixels -- channel meaning, ordering, size\n"
"                      # taken from the list of strings in include/sensor_msgs/image_encodings.h\n"
"\n"
"uint8 is_bigendian    # is this data bigendian?\n"
"uint32 step           # Full row length in bytes\n"
"uint8[] data          # actual matrix data, size is (step * rows)\n"
;
  }

  static const char* value(const ::perception::Objects_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::perception::Objects_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.objects);
      stream.next(m.frame);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Objects_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::perception::Objects_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::perception::Objects_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "objects[]" << std::endl;
    for (size_t i = 0; i < v.objects.size(); ++i)
    {
      s << indent << "  objects[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::perception::Object_<ContainerAllocator> >::stream(s, indent + "    ", v.objects[i]);
    }
    s << indent << "frame: ";
    s << std::endl;
    Printer< ::sensor_msgs::Image_<ContainerAllocator> >::stream(s, indent + "  ", v.frame);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PERCEPTION_MESSAGE_OBJECTS_H
